# Generated by Django 5.0.2 on 2024-02-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categories',
            new_name='category',
        ),
    ]
